=== bergerbd/roar-net-api-generator/packages/vscode-extension/schemas/project-config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "ROAR-NET API Generator Configuration",
  "type": "object",
  "required": [
    "api-model",
    "variability-model",
    "mapping-model",
    "templates",
    "output-folder"
  ],
  "additionalProperties": false,
  "properties": {
    "api-model": {
      "type": "string",
      "description": "Path of the API ecore model."
    },
    "variability-model": {
      "type": "string",
      "description": "Path to the varibility model."
    },
    "mapping-model": {
      "type": "string",
      "description": "Path to the mapping model."
    },
    "templates": {
      "type": "array",
      "description": "List of the templates to use.",
      "items": {
        "type": "object",
        "required": ["template", "folder"],
        "additionalProperties": false,
        "properties": {
          "template": {
            "type": "string",
            "description": "Template name."
          },
          "folder": {
            "type": "string",
            "description": "Path of the template folder."
          },
          "options": {
            "type": "object",
            "description": "Template-specific options."
          }
        }
      }
    },
    "output-folder": {
      "type": "string",
      "description": "Target folder for the generator.."
    }
  }
}

=== bergerbd/roar-net-api-generator/playground/roar-net.config.json
{
    "api-model": "roar-net-api.ecore",
    "variability-model": "roar-net-variability.uvl",
    "mapping-model": "variability-mapping.json",
    "templates": [
        {
            "template": "markdown",
            "folder": "templates/markdown",
            "options": {}
        },
        {
            "template": "java",
            "folder": "templates/java",
            "options": {
                "base-package": "roar_net"
            }
        }
    ],
    "output-folder": "generated"
}
